import { mkdirSync, readFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const projectRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const solverPath = resolve(
  projectRoot,
  'registry/scientific-calculator/solver/solver.py',
)
const outputPath = resolve(
  projectRoot,
  'registry/scientific-calculator/generated/solver-source.ts',
)
const source = readFileSync(solverPath, 'utf8')

mkdirSync(dirname(outputPath), { recursive: true })
await Bun.write(
  outputPath,
  `// Generated by scripts/render-solver-source.ts.\nexport const SOLVER_SOURCE = ${JSON.stringify(source)}\n`,
)
